site_name: Computação em Nuvem 2024.2
nav:
  - Projeto: index.md
  - YouTube API v3 - Chave da API: yt_api.md

repo_url: https://github.com/kadu-ymd/projeto-cloud
repo_name: projeto-cloud

theme: 
  name: material
  user_color_mode_toggle: true
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
plugins:
  - glightbox

  